# Generated by Django 3.2.13 on 2022-05-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Please write something!', max_length=30)),
                ('body', models.CharField(default='Please write something!', max_length=300)),
            ],
        ),
    ]
